import { PRODUCT_IMAGES } from './constants';
import type { Product, Order, User } from './types';

export const dummyProducts: Product[] = [
  {
    id: 'p1',
    name: 'WipeClean All-Purpose Spray',
    price: 249.00,
    description: 'Powerful all-purpose cleaning spray that cuts through grease, grime, and dirt. Safe for all surfaces including countertops, appliances, and glass. Fresh citrus scent leaves your home smelling clean.',
    image: PRODUCT_IMAGES.spray1,
    category: 'Surface Cleaners',
    stock: 150,
    featured: true,
    topSelling: true,
    rating: 4.8,
    soldCount: 1240,
  },
  {
    id: 'p2',
    name: 'EcoFresh Green Spray Bottle',
    price: 189.00,
    description: 'Eco-friendly reusable spray bottle made from recycled materials. Perfect for mixing your own cleaning solutions. Ergonomic trigger for comfortable use.',
    image: PRODUCT_IMAGES.spray2,
    category: 'Accessories',
    stock: 200,
    featured: true,
    topSelling: false,
    rating: 4.5,
    soldCount: 856,
  },
  {
    id: 'p3',
    name: 'PrecisionClean Nozzle Sprayer',
    price: 159.00,
    description: 'Precision nozzle spray system for targeted cleaning. Adjustable spray pattern from fine mist to concentrated stream. Ideal for hard-to-reach areas.',
    image: PRODUCT_IMAGES.spray3,
    category: 'Accessories',
    stock: 120,
    featured: false,
    topSelling: false,
    rating: 4.3,
    soldCount: 432,
  },
  {
    id: 'p4',
    name: 'PureWhite Surface Cleaner',
    price: 329.00,
    description: 'Premium surface cleaner with advanced whitening formula. Removes tough stains from tiles, grout, and porcelain. Antibacterial protection lasts up to 24 hours.',
    image: PRODUCT_IMAGES.cleaner1,
    category: 'Surface Cleaners',
    stock: 90,
    featured: true,
    topSelling: true,
    rating: 4.9,
    soldCount: 2105,
  },
  {
    id: 'p5',
    name: 'Complete Cleaning Kit Pro',
    price: 899.00,
    description: 'Professional-grade cleaning kit with everything you need. Includes brushes, microfiber cloths, cleaning solutions, and a premium carrying case. Perfect for deep cleaning sessions.',
    image: PRODUCT_IMAGES.kit1,
    category: 'Cleaning Kits',
    stock: 45,
    featured: true,
    topSelling: true,
    rating: 4.7,
    soldCount: 678,
  },
  {
    id: 'p6',
    name: 'DarkMaster Cleaning Set',
    price: 599.00,
    description: 'Sleek black cleaning set with premium spray bottles and professional brushes. Designed for commercial and residential use. Comes in an elegant presentation box.',
    image: PRODUCT_IMAGES.kit2,
    category: 'Cleaning Kits',
    stock: 60,
    featured: false,
    topSelling: true,
    rating: 4.6,
    soldCount: 934,
  },
  {
    id: 'p7',
    name: 'StainBuster Odor Remover',
    price: 279.00,
    description: 'Industrial-strength stain and odor remover. Eliminates pet stains, food spills, and tough odors. Bio-enzymatic formula breaks down organic matter completely.',
    image: PRODUCT_IMAGES.stainRemover,
    category: 'Disinfectants',
    stock: 180,
    featured: true,
    topSelling: false,
    rating: 4.4,
    soldCount: 567,
  },
  {
    id: 'p8',
    name: 'KitchenShine Degreaser',
    price: 219.00,
    description: 'Heavy-duty kitchen degreaser that tackles baked-on grease and food residue. Safe for stainless steel, ovens, and stovetops. No harsh chemical smell.',
    image: PRODUCT_IMAGES.spray1,
    category: 'Kitchen Cleaners',
    stock: 130,
    featured: false,
    topSelling: false,
    rating: 4.5,
    soldCount: 389,
  },
  {
    id: 'p9',
    name: 'BathBright Tile Cleaner',
    price: 199.00,
    description: 'Specially formulated for bathroom tiles, fixtures, and glass. Removes soap scum, hard water stains, and mildew. Leaves surfaces sparkling clean.',
    image: PRODUCT_IMAGES.cleaner1,
    category: 'Bathroom Cleaners',
    stock: 110,
    featured: false,
    topSelling: false,
    rating: 4.2,
    soldCount: 298,
  },
  {
    id: 'p10',
    name: 'FloorGlow Multi-Surface Polish',
    price: 449.00,
    description: 'Premium floor polish suitable for hardwood, laminate, tile, and marble. Creates a protective shine that repels dirt and lasts for weeks. Low-VOC formula.',
    image: PRODUCT_IMAGES.kit2,
    category: 'Floor Care',
    stock: 75,
    featured: true,
    topSelling: false,
    rating: 4.6,
    soldCount: 521,
  },
  {
    id: 'p11',
    name: 'UltraDisinfect Hospital Grade',
    price: 389.00,
    description: 'Hospital-grade disinfectant that kills 99.99% of bacteria and viruses. EPA registered and approved. Ideal for high-touch surfaces and sensitive environments.',
    image: PRODUCT_IMAGES.spray2,
    category: 'Disinfectants',
    stock: 200,
    featured: false,
    topSelling: true,
    rating: 4.8,
    soldCount: 1567,
  },
  {
    id: 'p12',
    name: 'MicroFiber Deluxe Cloth Set (6pc)',
    price: 349.00,
    description: 'Set of 6 ultra-soft microfiber cloths in assorted colors. Machine washable and reusable hundreds of times. Each cloth is color-coded for different areas.',
    image: PRODUCT_IMAGES.kit1,
    category: 'Accessories',
    stock: 250,
    featured: false,
    topSelling: false,
    rating: 4.4,
    soldCount: 712,
  },
];

export const dummyUsers: User[] = [
  {
    id: 'u1',
    email: 'maria.santos@gmail.com',
    fullName: 'Maria Santos',
    phone: '+63 912 345 6789',
    address: '123 Rizal St., Brgy. Poblacion, Makati City, Metro Manila',
    isAdmin: false,
    verified: true,
    createdAt: '2024-11-15T08:30:00Z',
  },
  {
    id: 'u2',
    email: 'juan.delacruz@gmail.com',
    fullName: 'Juan Dela Cruz',
    phone: '+63 917 654 3210',
    address: '456 Mabini Ave., Brgy. San Antonio, Quezon City, Metro Manila',
    isAdmin: false,
    verified: true,
    createdAt: '2024-12-01T10:00:00Z',
  },
  {
    id: 'u3',
    email: 'admin@wipeitgood.com',
    fullName: 'Admin User',
    phone: '+63 918 999 0000',
    address: 'Wipe It Good Trading HQ, Taguig City',
    isAdmin: true,
    verified: true,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'u4',
    email: 'ana.reyes@gmail.com',
    fullName: 'Ana Reyes',
    phone: '+63 920 111 2222',
    address: '789 Bonifacio Blvd., Brgy. Kapitolyo, Pasig City',
    isAdmin: false,
    verified: true,
    createdAt: '2025-01-10T14:20:00Z',
  },
];

export const dummyOrders: Order[] = [
  {
    id: 'ORD-2025-001',
    userId: 'u1',
    userName: 'Maria Santos',
    userEmail: 'maria.santos@gmail.com',
    userPhone: '+63 912 345 6789',
    userAddress: '123 Rizal St., Brgy. Poblacion, Makati City, Metro Manila',
    items: [
      { product: dummyProducts[0], quantity: 2 },
      { product: dummyProducts[4], quantity: 1 },
    ],
    total: 1397.00,
    status: 'Delivered',
    paymentMethod: 'GCash',
    createdAt: '2025-01-20T09:15:00Z',
    updatedAt: '2025-01-25T14:30:00Z',
  },
  {
    id: 'ORD-2025-002',
    userId: 'u2',
    userName: 'Juan Dela Cruz',
    userEmail: 'juan.delacruz@gmail.com',
    userPhone: '+63 917 654 3210',
    userAddress: '456 Mabini Ave., Brgy. San Antonio, Quezon City, Metro Manila',
    items: [
      { product: dummyProducts[3], quantity: 3 },
      { product: dummyProducts[6], quantity: 1 },
    ],
    total: 1266.00,
    status: 'Shipped',
    paymentMethod: 'COD',
    createdAt: '2025-02-01T11:00:00Z',
    updatedAt: '2025-02-03T08:00:00Z',
  },
  {
    id: 'ORD-2025-003',
    userId: 'u1',
    userName: 'Maria Santos',
    userEmail: 'maria.santos@gmail.com',
    userPhone: '+63 912 345 6789',
    userAddress: '123 Rizal St., Brgy. Poblacion, Makati City, Metro Manila',
    items: [
      { product: dummyProducts[5], quantity: 1 },
    ],
    total: 599.00,
    status: 'Confirmed',
    paymentMethod: 'GCash',
    createdAt: '2025-02-10T16:45:00Z',
    updatedAt: '2025-02-11T09:00:00Z',
  },
  {
    id: 'ORD-2025-004',
    userId: 'u4',
    userName: 'Ana Reyes',
    userEmail: 'ana.reyes@gmail.com',
    userPhone: '+63 920 111 2222',
    userAddress: '789 Bonifacio Blvd., Brgy. Kapitolyo, Pasig City',
    items: [
      { product: dummyProducts[1], quantity: 2 },
      { product: dummyProducts[10], quantity: 1 },
      { product: dummyProducts[11], quantity: 1 },
    ],
    total: 1116.00,
    status: 'Pending',
    paymentMethod: 'COD',
    createdAt: '2025-02-14T13:20:00Z',
    updatedAt: '2025-02-14T13:20:00Z',
  },
  {
    id: 'ORD-2025-005',
    userId: 'u2',
    userName: 'Juan Dela Cruz',
    userEmail: 'juan.delacruz@gmail.com',
    userPhone: '+63 917 654 3210',
    userAddress: '456 Mabini Ave., Brgy. San Antonio, Quezon City, Metro Manila',
    items: [
      { product: dummyProducts[9], quantity: 2 },
      { product: dummyProducts[7], quantity: 1 },
    ],
    total: 1117.00,
    status: 'Pending',
    paymentMethod: 'GCash',
    createdAt: '2025-02-15T10:00:00Z',
    updatedAt: '2025-02-15T10:00:00Z',
  },
];
